import React, { Component } from 'react'
import Search from './Search.js'
import SearchAutoComplete from './SearchAutoComplete'

export default class SearchWrapper extends Component {
    render() {
        const suggestions = [
            "Greg Kramer",
    "Gareth Cawley",
    "Bill Banaag",
    "Matthew Galloway",
    "Chris Loat",
    "Darrel Nantais",
    "Jacob Slan",
    "Kieran Bol",
    "Polly Yung",
    "Aaron Hooper",
    "Chris Wang",
    "Julian Weinrib",
    "Marianne Perko",
    "Baron Lam",
    "Rob Grundy",
    "Jeff Chik",
    "Colin Mattison",
    "Ian Bone",
    "Anthea Tsoukalas",
    "Remi Jr. Ojo",
    "Neil Duchen",
    "Norman Lew",
    "Mark Virata",
    "Charles Burger",
    "Jessica Jia",
    "Nathaniel Faries",
    "Peter Hawkings",
    "Blue McClellan",
    "Andrew Gosbee",
    "Laurie Zacour",
    "Mathew Harder",
    "Destin McQuillan",
    "Noah Goldstein",
    "Anthony Slater",
    "Agatha Hodsman",
    "Tyler Curtis",
    "Misiu Godfrey",
    "Keegan Lee-Newbury",
    "Jason Chan",
    "Amanda Murdoch",
    "Jean-Francois Ouellet",
    "Eric Palmitesta",
    "Robert Jackson",
    "Vikki Shimoda",
    "Gabriel Isaac",
    "Cristina Chern",
    "Jeff Steele",
    "Mark Taylor",
    "Tyler Longo",
    "David Burden",
    "Colin Thompson",
    "Travis DeWolf",
    "Lucy Chu",
    "David Yu",
    "Taunya Tremblay",
    "Carolina Vargas",
    "Vincent Poon",
    "Greg McMullin",
    "Kirk MacRae",
    "Marko Iskric",
    "Timothy Fowler",
    "Saleh Mohamed",
    "Matt Denton",
    "Rick St. Jean",
    "Michael McConnell",
    "Leroy Lo",
    "Will Mercer",
    "David Ip",
    "Patrick Russell",
    "Jennifer Law",
    "Chris Faulkner",
    "Stephanie Schwartz",
    "Matt Kishi",
    "John Hurlbut",
    "Kenny Ye",
    "Genevieve Daigle",
    "Lachlan Holmes",
    "Meghan Janssen",
    "Finlay D'silva",
    "Jill Elliot",
    "Hin Tang",
    "Debra Cohen",
    "Andrew Milne",
    "Jessica Chen",
    "Ed Kung",
    "Cathy Wong",
    "Emma Seaborn",
    "Jarel Villarroya",
    "Benjamin St.Louis",
    "Don Colangelo",
    "Carter Chin",
    "Benjamin Goodman",
    "Julie DeWolf",
    "Ben Kirkland",
    "Amanda Sheppard",
    "Valerie MacDougall",
    "Matthew Colphon",
    "William Peckham",
    "Carson Pun",
    "Peter Ferderber",
    "Wesley George",
    "Brittany Heath",
    "Maxim Tomashevsky",
    "Michael Rudanycz",
    "Jon Jephcott",
    "Ikram Mustapha",
    "Daniel McKittrick",
    "Dario Zgrablic",
    "Jon Brandt",
    "Andrew Fell",
    "Heidi Siu",
    "Lindsay Musalem",
    "Marisa Hart",
    "Jonathan Brunetti",
    "Raoul Tanyan",
    "Stephanie Harper",
    "Diane Sepa-Kishi",
    "Adam Wenneman",
    "Hadiya Roderique",
    "Sarah Burke",
    "Kalu Kalu",
    "Kyle Hubbard",
    "Ron Waisbord",
    "Allan Tong",
    "Nick Hung",
    "Natalie Fitzgerald",
    "Tom Brooks",
    "Eli Fidler",
    "Puja Ahluwalia",
    "Stephanie Kimmerle",
    "Dexter Chu",
    "Danielle Leung",
    "Kristie Ellis",
    "Lori Bristow",
    "Alyne Azucena",
    "Anna Luo",
    "Kat Zikov (Johnson)",
    "Ronald Ha",
    "Daniel Eisner",
    "Daniel Wagner",
    "Janine Duffy",
    "Norman Stewart",
    "Mark Kalvaitis",
    "Daniel Ngai",
    "Janet Wan",
    "Laura Wiese",
    "Beth Fisher",
    "Diane Pendlebury",
    "Anita Benoit",
    "Anne-Marie Carey",
    "James Ho",
    "Cameron Crockatt",
    "Tabish Gilani",
    "Catherine Chao",
    "Crystal Sotelo",
    "Krista Bennatti-Roberts",
    "Kaity Williams",
    "Graham Haines",
    "Ameet Khanderia",
    "Rebecca Chan",
    "Anders Whist",
    "John Spears",
    "Natalie Dunn",
    "Dawn Man",
    "Morgan Leech",
    "Lydia Dwyer",
    "Helen OSullivan",
    "Farra Kurniawan"
        ];

        return (
            <div>
                <SearchAutoComplete suggestions = { suggestions }></SearchAutoComplete>
                {/* <Search suggestions = { suggestions }></Search> */}
            </div>
        )
    }
}
